#!name= YouTube Premium (Yuleang)
#!desc= By: Yuleang (English Version)
#!arguments=Block Upload:true,Block Immersive:true,Subtitle Lang:en,Lyrics Lang:en,Script Engine:jsc,Debug Mode:false
#!arguments-desc=- Block Parameters: [true, false] \n- Translation Parameters: [Language Code, off] \n- Script Engine: [auto, jsc, webview]\n\n1. Language codes follow Google Translate (e.g., en, kh, zh). Set to 'off' to disable translation.\n2. Recommended to use 'jsc' engine.\n3. Enable Debug Mode only for troubleshooting logs.

# > Note
# PiP (Picture-in-Picture) and Background Play must be turned on in YouTube Settings:
#   - Settings -> General -> Picture-in-Picture
#   - Settings -> Background & Downloads -> Background Play

[Rule]
AND,((DOMAIN-SUFFIX,googlevideo.com), (PROTOCOL,UDP)),REJECT
AND,((DOMAIN,youtubei.googleapis.com), (PROTOCOL,UDP)),REJECT

[Script]
youtube.request = type=http-request,pattern=^https:\/\/youtubei\.googleapis\.com\/youtubei\/v1\/(browse|next|player|reel\/reel_watch_sequence|get_watch),requires-body=1,max-size=-1,binary-body-mode=1,engine={{{Script Engine}}},script-path=https://raw.githubusercontent.com/BigBossCoderTrader/YouTube_Premium_module/refs/heads/main/youtube.request.preview.js
youtube.response = type=http-response,pattern=^https:\/\/youtubei\.googleapis\.com\/youtubei\/v1\/(browse|next|player|search|reel\/reel_watch_sequence|guide|account\/get_setting|get_watch),requires-body=1,max-size=-1,binary-body-mode=1,engine={{{Script Engine}}},script-path=https://raw.githubusercontent.com/BigBossCoderTrader/YouTube_Premium_module/refs/heads/main/youtube.response.preview.js,argument="{"lyricLang":"{{{Lyrics Lang}}}","captionLang":"{{{Subtitle Lang}}}","blockUpload":{{{Block Upload}}},"blockImmersive":{{{Block Immersive}}},"debug":{{{Debug Mode}}}}"

[Map Local]
^https?:\/\/[\w-]+\.googlevideo\.com\/initplayback.+&oad data-type=text data=""

[MITM]
hostname = %APPEND% *.googlevideo.com, youtubei.googleapis.com
